java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/testNG_Browser_chrome.xml
java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/testNG_Config.xml
java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/Test_Batch_Parallel_1_No1to100.xml
java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/Test_Batch_Parallel_1_No101to200.xml
java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/Test_Batch_Parallel_1_No201to300.xml
java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/Test_Batch_Parallel_1_No301to400.xml
java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/Test_Batch_Parallel_1_No401to431.xml
java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/Test_Batch_Serial_1_No1to100.xml
java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/Test_Batch_Serial_1_No101to200.xml
java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/Test_Batch_Serial_1_No201to300.xml
java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/Test_Batch_Serial_1_No301to357.xml
java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/testNG_Browser_firefox.xml
java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/testNG_Config.xml
java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/Test_Batch_Parallel_1_No1to100.xml
java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/Test_Batch_Parallel_1_No101to200.xml
java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/Test_Batch_Parallel_1_No201to300.xml
java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/Test_Batch_Parallel_1_No301to400.xml
java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/Test_Batch_Parallel_1_No401to431.xml
java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/Test_Batch_Serial_1_No1to100.xml
java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/Test_Batch_Serial_1_No101to200.xml
java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/Test_Batch_Serial_1_No201to300.xml
java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/Test_Batch_Serial_1_No301to357.xml
java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/testNG_Browser_ie.xml
java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/testNG_Config_IE.xml
java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/Test_Batch_Parallel_1_IE_No1to100.xml
java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/Test_Batch_Parallel_1_IE_No101to200.xml
java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/Test_Batch_Parallel_1_IE_No201to300.xml
java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/Test_Batch_Parallel_1_IE_No301to400.xml
java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/Test_Batch_Parallel_1_IE_No401to431.xml
java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/Test_Batch_Serial_1_IE_1to100.xml
java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/Test_Batch_Serial_1_IE_101to200.xml
java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/Test_Batch_Serial_1_IE_201to300.xml
java -cp "JarFiles\*;bin" org.testng.TestNG ./TestNGXMLs/Test_Batch_Serial_1_IE_301to357.xml
